### PR TITLE
Added JSON -> DOM parser, and test case.

### PR DESCRIPTION
**Pull request by coderextreme**
Reasoning.  We need a JSON -> DOM converter, if we want to support JSON

This patch is released to the public domain.

### CODE REVIEW

**Comment by DRx3D** [comment]
CoderExtreme, I think this best fits in the 'utils' directory. Because it is not in the xseen object and it (theoretically) could have a drop-in replacement. I am not sure how best to make that change.

**Comment by coderextreme** [comment]
I moved JSONParser.js to the src/utils folder.  I changed json-test.html to have the JSON example present in the code.  It loads the JSON into the XML, but for some reason, it does not display in a canvas.  In X3DOM, I would call x3dom.reload().  I am not sure what the correct thing to do is.

**Comment by coderextreme** [comment]
I also changed xmlToJson() to support a -children property, so that reordering is not necessary.

**Comment by coderextreme** [comment]
I have modified the pull request.

John

Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
New change adds xseen.reload();   We need to remove the old text area still.  Animation works

**Pull request merged**
